/**
 * CSV Generation & Export Utilities for EBPLS Superadmin Reports.
 * Ensures downloaded CSVs are immediately understandable in Excel, Google Sheets,
 * and text editors with proper UTF-8 BOM encoding, clean column headers, and escaped fields.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface CsvColumn<T = any> {
  key: keyof T | string;
  label: string;
  format?: (value: any, row: T) => string;
}

/**
 * Escapes a single cell value according to RFC 4180:
 * - If value is null, undefined, or empty -> returns empty string
 * - If value contains commas, quotes, newlines -> escapes quotes as "" and wraps in quotes
 * - Formats dates to readable YYYY-MM-DD HH:mm:ss
 * - Formats booleans to Yes / No
 */
export function escapeCsvCell(value: unknown): string {
  if (value === null || value === undefined) {
    return "";
  }

  if (typeof value === "boolean") {
    return value ? "Yes" : "No";
  }

  if (value instanceof Date) {
    if (isNaN(value.getTime())) return "";
    return value.toISOString().replace("T", " ").replace(/\.\d{3}Z$/, "");
  }

  const str = String(value).trim();

  // If the cell contains comma, quote, or newline, escape and quote it
  if (str.includes(",") || str.includes('"') || str.includes("\n") || str.includes("\r")) {
    return `"${str.replace(/"/g, '""')}"`;
  }

  return str;
}

/**
 * Generates a full CSV string with UTF-8 BOM (\uFEFF) for Microsoft Excel compatibility.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function buildCsvContent<T = any>(
  columns: CsvColumn<T>[],
  rows: T[],
  options?: {
    reportTitle?: string;
    generatedAt?: string;
    generatedBy?: string;
    dateRange?: string;
  }
): string {
  const lines: string[] = [];

  // Optional clear metadata header rows at the top for context
  if (options?.reportTitle) {
    lines.push(`"# REPORT: ${options.reportTitle}"`);
    lines.push(`"# MUNICIPALITY: Municipality of Enrique B. Magalona (BPLO)"`);
    if (options.generatedAt) lines.push(`"# GENERATED AT: ${options.generatedAt}"`);
    if (options.generatedBy) lines.push(`"# GENERATED BY: ${options.generatedBy}"`);
    if (options.dateRange) lines.push(`"# PERIOD: ${options.dateRange}"`);
    lines.push(""); // empty row before column headers
  }

  // Column Headers
  const headerLine = columns.map((col) => escapeCsvCell(col.label)).join(",");
  lines.push(headerLine);

  // Data Rows
  for (const row of rows) {
    const rowValues = columns.map((col) => {
      const rawVal = (row as Record<string, unknown>)[col.key as string];
      if (col.format) {
        return escapeCsvCell(col.format(rawVal, row));
      }
      return escapeCsvCell(rawVal);
    });
    lines.push(rowValues.join(","));
  }

  // Prepend UTF-8 BOM so Excel opens with proper encoding
  return "\uFEFF" + lines.join("\r\n");
}

/**
 * Triggers a client-side CSV download from a CSV string.
 */
export function triggerCsvBlobDownload(filename: string, csvContent: string): void {
  const safeName = filename.endsWith(".csv") ? filename : `${filename}.csv`;
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const objectUrl = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = objectUrl;
  link.setAttribute("download", safeName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(objectUrl), 1000);
}
