"use client";

import type { ReportMetadata } from "@/lib/printable-reports";
import { MunicipalDocumentHeader } from "@/components/ui/municipal-document-header";

interface ReportPageHeaderProps {
  meta: ReportMetadata;
  /** Override back button behavior. Defaults to window.history.back(). */
  onBack?: () => void;
  /** Override print button behavior. Defaults to window.print(). */
  onPrint?: () => void;
  /** If provided, renders an <a> link instead of a button for the back action. */
  backHref?: string;
  /** If provided, renders a direct CSV download link. */
  csvExportUrl?: string;
  /** Custom handler for CSV download. */
  onDownloadCsv?: () => void;
  /** Page orientation for printing ('portrait' | 'landscape'). Defaults to 'portrait'. */
  orientation?: "portrait" | "landscape";
}

/**
 * Shared printable report header for IT Administrator system reports.
 * Uses the same municipal heading layout as the Business Permit printout.
 */
export function ReportPageHeader({
  meta,
  onBack,
  onPrint,
  backHref,
  csvExportUrl,
  onDownloadCsv,
  orientation = "portrait",
}: ReportPageHeaderProps) {
  return (
    <>
      <div className="no-print mb-4 flex items-center justify-between gap-3">
        {backHref ? (
          <a
            href={backHref}
            className="inline-flex items-center gap-1 rounded-lg border border-[var(--border-color)] bg-white px-3 py-2 text-sm font-semibold text-[var(--foreground)] hover:bg-[var(--muted-surface)]"
          >
            ← Back to Reports
          </a>
        ) : (
          <button
            type="button"
            onClick={onBack ?? (() => window.history.back())}
            className="inline-flex items-center gap-1 rounded-lg border border-[var(--border-color)] bg-white px-4 py-2 text-sm font-semibold text-[var(--foreground)] hover:bg-[var(--muted-surface)]"
          >
            ← Back
          </button>
        )}

        <div className="flex items-center gap-2">
          {csvExportUrl ? (
            <a
              href={csvExportUrl}
              download
              className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--border-color)] bg-white px-3 py-1.5 text-sm font-semibold text-[var(--foreground)] hover:bg-[var(--muted-surface)] transition-colors shadow-xs"
              title="Download report dataset as Excel-compatible CSV file"
            >
              <span>📥</span>
              <span>Download CSV</span>
            </a>
          ) : onDownloadCsv ? (
            <button
              type="button"
              onClick={onDownloadCsv}
              className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--border-color)] bg-white px-3 py-1.5 text-sm font-semibold text-[var(--foreground)] hover:bg-[var(--muted-surface)] transition-colors shadow-xs"
              title="Download report dataset as Excel-compatible CSV file"
            >
              <span>📥</span>
              <span>Download CSV</span>
            </button>
          ) : null}

          <button
            type="button"
            onClick={onPrint ?? (() => window.print())}
            className="inline-flex items-center gap-2 rounded-lg border border-black px-3 py-1.5 text-sm font-semibold text-black hover:bg-neutral-100 transition-colors"
          >
            <span>🖨️</span>
            <span>Print Report</span>
          </button>
        </div>
      </div>

      <MunicipalDocumentHeader
        heading={{
          municipality: meta.municipality,
          office: meta.office,
          title: meta.title,
        }}
        titleTone="official"
        meta={
          <div className="space-y-1">
            <p>
              <strong>Period Covered:</strong> {meta.dateRange}
            </p>
            <p>
              <strong>Generated by:</strong> {meta.generatedBy}
            </p>
            <p>
              <strong>Generated at:</strong> {meta.generatedAt}
            </p>
          </div>
        }
      />

      <style jsx global>{`
        @page {
          size: A4 ${orientation};
          margin: ${orientation === "landscape" ? "8mm 8mm" : "14mm 12mm"};
        }

        @media print {
          html,
          body {
            background: #ffffff !important;
            width: 100% !important;
          }

          .no-print,
          nav,
          aside,
          .app-header,
          [data-app-chrome],
          [data-navigation],
          [data-sidebar] {
            display: none !important;
          }

          .report-print-container {
            max-width: 100% !important;
            width: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
          }

          .report-table-row {
            page-break-inside: avoid;
          }

          .report-page-break {
            page-break-before: always;
          }

          /* Detailed records table print layout */
          .report-table-wrapper {
            overflow: visible !important;
            width: 100% !important;
            max-width: 100% !important;
          }

          .report-table-wrapper table,
          table.report-table {
            width: 100% !important;
            max-width: 100% !important;
            table-layout: auto !important;
            border-collapse: collapse !important;
          }

          .report-table-wrapper th,
          table.report-table th {
            font-size: 9.5px !important;
            padding: 3px 4px !important;
            line-height: 1.25 !important;
            white-space: normal !important;
            word-break: break-word !important;
          }

          .report-table-wrapper td,
          table.report-table td {
            font-size: 9.5px !important;
            line-height: 1.25 !important;
            padding: 3px 4px !important;
            word-break: break-word !important;
            overflow-wrap: break-word !important;
          }

          /* In print, allow table cells to wrap to fit page width while preserving on-screen whitespace-nowrap */
          .report-table-wrapper td.whitespace-nowrap:not(.font-mono),
          table.report-table td.whitespace-nowrap:not(.font-mono) {
            white-space: normal !important;
          }

          .report-table-wrapper td.font-mono,
          table.report-table td.font-mono {
            font-size: 9px !important;
            white-space: nowrap !important;
          }
        }
      `}</style>
    </>
  );
}
